### PR TITLE
Upgrade to 0.9.12

### PR DESCRIPTION
**Pull request by umateusz**
I quickly prepared a version for 0.9.12. I ran it in docker and it looks good.

### CODE REVIEW

**Comment by mjxu96** [comment]
Awesome! Have you tried running the example Python script and is there anything wired?

**Comment by umateusz** [comment]
It looks good but to be honest I have never run this script before.

**Comment by mjxu96** [comment]
Hi @umateusz thanks for the contribution! I will merge it ASAP after testing it.

**Comment by mjxu96** [comment]
Hi I've tested it and it looks good. Thanks.

**Pull request merged**
